#pragma once

#include <integrators/Integrator.h>
#include <Actor.h>
#include <vector>
#include <Texture.h>
#include <Parameters.h>
#include <Parameters.h>

class DebugRenderer : public Integrator {
public:
	DebugRenderer(Parameters& params);
	
	// Double for loop doing calls to trace for each ray generated by pixel and sample
	void Render();

	// Traces a ray recursively and returns an accumulated color
	glm::vec3 trace(Ray& ray);

	// Properties for GUI
	void GUISettings();
private:
	Parameters& p;
	int samples = 1;
};